title: The Axis of Stevil Show and Tell
email: steven@axisofstevil.com
description: >
  The Axis of Stevil Show and Tell will show you the best things to see
  on the internet, show you the worst things to see on the internet,
  and show you some things you didn't know existed.
baseurl: ""
url: "https://www.axisofstevilshow.com"

# Build settings
markdown: kramdown

permalink: /show/:path
