title: The Axis of Stevil Show
email: steven@axisofstevil.com
description: >
  The Axis of Stevil Show will show you the best things to see
  on the internet, show you the worst things to see on the internet,
  and show you some things you didn't know existed.
baseurl: ""
url: "https://www.axisofstevilshow.com"

contact_address:
  - '228 Park Ave S #66165'
  - 'New York, NY 10003-1502'
  - 'USA'

# Build settings
markdown: kramdown

permalink: /show/:path
